# Generated by Django 5.2 on 2025-05-16 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_event_recurrence_alter_event_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='event_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
